### ISSUE TITLE
Question Request for Brain Hurt Games

### ISSUE THREAD

**Issue by Guzza32** [larrystudios/brainhurtgames#13]
Question : Where do you survive?
Answer 1 : Ice island
Answer 2 : Lava island
Answer 3 : 30,000 years ago
Correct : Lava island
Difficulty : Insane
![IMG_1589](https://user-images.githubusercontent.com/95211059/144347990-8612d8b3-02ca-44b0-922b-f2a9336d05b7.jpeg)
That’s because you have fire blocking poison.

**Comment by kornrt2018** [comment]
Cool! Will add it in v2.5.0 Beta 12.

**Comment by kornls** [comment]
Sorry—We forgot to add this to the game. We’ll make sure to include it in v3.0.0 Alpha 1.
