### ISSUE TITLE
New question request

### ISSUE THREAD

**Issue by Arayasing** [larrystudios/brainhurtgames#16]
Question:  Hiragana 
                chi + ro ko
Answer 1 : 8
Answer 2 : 532
Correct : 8
Difficulty : Normal

**Comment by kornls** [comment]
:+1: - We’ll add that in the next version!

**Comment by kornls** [comment]
Sorry, we forgot to add this question to the game. We’ll make sure to add it in the next version (v3.0.0 Alpha 1)!
